//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MfxDemo3.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_Core {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_Core() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MfxDemo3.Resources.Strings_Core", typeof(Strings_Core).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about one month ago.
        /// </summary>
        public static string Date_AboutOneMonthAgo {
            get {
                return ResourceManager.GetString("Date_AboutOneMonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about two weeks ago.
        /// </summary>
        public static string Date_AboutTwoWeeksAgo {
            get {
                return ResourceManager.GetString("Date_AboutTwoWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expired.
        /// </summary>
        public static string Date_Expired {
            get {
                return ResourceManager.GetString("Date_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one month.
        /// </summary>
        public static string Date_InAboutOneMonth {
            get {
                return ResourceManager.GetString("Date_InAboutOneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about two weeks.
        /// </summary>
        public static string Date_InAboutTwoWeeks {
            get {
                return ResourceManager.GetString("Date_InAboutTwoWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string Date_InfoNotAvailable {
            get {
                return ResourceManager.GetString("Date_InfoNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months from now.
        /// </summary>
        public static string Date_InMonths {
            get {
                return ResourceManager.GetString("Date_InMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last week.
        /// </summary>
        public static string Date_LastWeek {
            get {
                return ResourceManager.GetString("Date_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months ago.
        /// </summary>
        public static string Date_MonthsAgo {
            get {
                return ResourceManager.GetString("Date_MonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next week.
        /// </summary>
        public static string Date_NextWeek {
            get {
                return ResourceManager.GetString("Date_NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string Date_Today {
            get {
                return ResourceManager.GetString("Date_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string Date_Tomorrow {
            get {
                return ResourceManager.GetString("Date_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string Date_Years {
            get {
                return ResourceManager.GetString("Date_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string Date_Yesterday {
            get {
                return ResourceManager.GetString("Date_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature not implemented yet.
        /// </summary>
        public static string System_NotImplementedYet {
            get {
                return ResourceManager.GetString("System_NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working ....
        /// </summary>
        public static string System_OperationInProgress {
            get {
                return ResourceManager.GetString("System_OperationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options available.
        /// </summary>
        public static string System_OptionsAvailable {
            get {
                return ResourceManager.GetString("System_OptionsAvailable", resourceCulture);
            }
        }
    }
}
