//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mfx2.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mfx2.Server.Resources.Strings_UI", typeof(Strings_UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change the password.&lt;br&gt;If the problem persists, please contact the administrator..
        /// </summary>
        public static string Account_CouldntChangePassword {
            get {
                return ResourceManager.GetString("Account_CouldntChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email to recover your password.
        /// </summary>
        public static string Account_EnterEmailToRecoverPassword {
            get {
                return ResourceManager.GetString("Account_EnterEmailToRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid email address.
        /// </summary>
        public static string Account_EnterYourEmail {
            get {
                return ResourceManager.GetString("Account_EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user name.
        /// </summary>
        public static string Account_EnterYourName {
            get {
                return ResourceManager.GetString("Account_EnterYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string Account_EnterYourPassword {
            get {
                return ResourceManager.GetString("Account_EnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Account_ForgotYourPassword {
            get {
                return ResourceManager.GetString("Account_ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify both user name and password.
        /// </summary>
        public static string Account_IncompleteCredentials {
            get {
                return ResourceManager.GetString("Account_IncompleteCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string Account_InvalidCredentials {
            get {
                return ResourceManager.GetString("Account_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string Account_PassworcChanged {
            get {
                return ResourceManager.GetString("Account_PassworcChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover password.
        /// </summary>
        public static string Account_RecoverPassword {
            get {
                return ResourceManager.GetString("Account_RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown user.
        /// </summary>
        public static string Account_UnknownUser {
            get {
                return ResourceManager.GetString("Account_UnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account locked.
        /// </summary>
        public static string Account_UserAccountLocked {
            get {
                return ResourceManager.GetString("Account_UserAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation failed miserably. Sorry about that!.
        /// </summary>
        public static string Generic_OperationFailure {
            get {
                return ResourceManager.GetString("Generic_OperationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation completed successfully..
        /// </summary>
        public static string Generic_OperationSuccess {
            get {
                return ResourceManager.GetString("Generic_OperationSuccess", resourceCulture);
            }
        }
    }
}
